#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 nu

''' this is a dev file used to cross match regions/cercles/communes
    between ANAMDB (numeric IDs) and XLSForm list (alpha IDs)

    for matching purpose, ANAM DB's list has been edited to match
    wording of xlsform and original wording kept as comment.

    only edit to xlsform is commenting 3 non-existing communes '''

xlscom = [
    ("abeibara", "ABEIBARA", "abeibara"),
    ("adarmalane", "ADARMALANE", "goundam"),
    ("adjelhoc", "ADJELHOC", "tessalit"),
    ("alafia", "ALAFIA", "tombouctou-cercle"),
    ("allahina", "ALLAHINA", "nara"),
    ("alzounoub", "ALZOUNOUB", "goundam"),
    ("anchawadi", "ANCHAWADI", "gao-cercle"),
    ("anderamboukane", "ANDERAMBOUKANE", "menaka"),
    ("anefif", "ANEFIF", "kidal-cercle"),
    ("ansongo", "ANSONGO", "ansongo"),
    ("arham", "ARHAM", "dire"),
    ("badia", "BADIA", "kita"),
    ("bafoulabe", "BAFOULABE", "bafoulabe"),
    ("baguindadougou", "BAGUINDADOUGOU", "segou-cercle"),
    ("baguineda-camp", "BAGUINEDA CAMP", "kati"),
    ("balan-bakana", "BALAN BAKANA", "kangaba"),
    ("bamafele", "BAMAFELE", "bafoulabe"),
    ("bamba", "BAMBA", "bourem"),
    ("bamba", "BAMBA", "koro"),
    ("bambara-maoude", "BAMBARA MAOUDE", "gourma-rharous"),
    ("banamba", "BANAMBA", "banamba"),
    ("banco", "BANCO", "dioila"),
    ("bancoumana", "BANCOUMANA", "kati"),
    ("bandiagara", "BANDIAGARA", "bandiagara"),
    ("bangassi", "BANGASSI", "kayes-cercle"),
    ("baniere-kore", "BANIERE KORE", "nioro"),
    ("banikane", "BANIKANE", "gourma-rharous"),
    ("banikane-narhawa", "BANIKANE NARHAWA", "niafunke"),
    ("bankass", "BANKASS", "bankass"),
    ("bara", "BARA", "ansongo"),
    ("bara-sara", "BARA SARA", "bandiagara"),
    ("baramandougou", "BARAMANDOUGOU", "san"),
    ("baraoueli", "BARAOUELI", "baraoueli"),
    ("barapireli", "BARAPIRELI", "koro"),
    ("bassirou", "BASSIROU", "mopti-cercle"),
    ("baya", "BAYA", "yanfolila"),
    ("baye", "BAYE", "bankass"),
    ("baye", "BAYE", "kenieba"),
    ("beguene", "BEGUENE", "bla"),
    ("bellen", "BELLEN", "segou-cercle"),
    ("bema", "BEMA", "diema"),
    ("bendougouba", "BENDOUGOUBA", "kita"),
    ("benena", "BENENA", "tominian"),
    ("benkadi", "BENKADI", "banamba"),
    ("benkadi", "BENKADI", "dioila"),
    ("benkadi", "BENKADI", "kangaba"),
    ("benkadi", "BENKADI", "sikasso-cercle"),
    ("benkadi-founia", "BENKADI FOUNIA", "kita"),
    ("ber", "BER", "tombouctou-cercle"),
    ("bimbere-tama", "BIMBERE TAMA", "youwarou"),
    ("binga", "BINGA", "dire"),
    ("binko", "BINKO", "dioila"),
    ("bintagoungou", "BINTAGOUNGOU", "goundam"),
    ("bla", "BLA", "bla"),
    ("bladie-tiemala", "BLADIE-TIEMALA", "bougouni"),
    ("blendio", "BLENDIO", "sikasso-cercle"),
    ("boghassa", "BOGHASSA", "abeibara"),
    ("boidie", "BOIDIE", "baraoueli"),
    ("boky-were", "BOKY WERE", "macina"),
    ("bolo-fouta", "BOLO FOUTA", "yanfolila"),
    ("bondo", "BONDO", "koro"),
    ("borko", "BORKO", "bandiagara"),
    ("boron", "BORON", "banamba"),
    ("borondougou", "BORONDOUGOU", "mopti-cercle"),
    ("bossofala", "BOSSOFALA", "kati"),
    ("boudofo", "BOUDOFO", "kita"),
    ("bougaribaya", "BOUGARIBAYA", "kita"),
    ("bougoula", "BOUGOULA", "kati"),
    ("bougoula", "BOUGOULA", "kolondieba"),
    ("boura", "BOURA", "yorosso"),
    ("bourem", "BOUREM", "bourem"),
    ("bourem-inaly", "BOUREM INALY", "tombouctou-cercle"),
    ("bourem-sidi-amar", "BOUREM SIDI AMAR", "dire"),
    ("bourra", "BOURRA", "ansongo"),
    ("boussin", "BOUSSIN", "segou-cercle"),
    ("cinzana", "CINZANA", "segou-cercle"),
    ("colombine", "COLOMBINE", "kayes-cercle"),
    ("commune-1", "COMMUNE 1", "district-de-bamako"),
    ("commune-2", "COMMUNE 2", "district-de-bamako"),
    ("commune-3", "COMMUNE 3", "district-de-bamako"),
    ("commune-4", "COMMUNE 4", "district-de-bamako"),
    ("commune-5", "COMMUNE 5", "district-de-bamako"),
    ("commune-6", "COMMUNE 6", "district-de-bamako"),
    ("commune-de-bougouni", "COMMUNE DE BOUGOUNI", "bougouni"),
    ("commune-de-gao", "COMMUNE DE GAO", "gao-cercle"),
    ("commune-de-kati", "COMMUNE DE KATI", "kati"),
    ("commune-de-kita", "COMMUNE DE KITA", "kita"),
    ("commune-de-koutiala", "COMMUNE DE KOUTIALA", "koutiala"),
    ("commune-de-mopti", "COMMUNE DE MOPTI", "mopti-cercle"),
    ("commune-de-nioro", "COMMUNE DE NIORO", "nioro"),
    ("commune-de-san", "COMMUNE DE SAN", "san"),
    ("commune-de-segou", "COMMUNE DE SEGOU", "segou-cercle"),
    ("commune-de-sikasso", "COMMUNE DE SIKASSO", "sikasso-cercle"),
    ("commune-de-tombouctou", "COMMUNE DE TOMBOUCTOU", "tombouctou-cercle"),
    ("commune-urbaine-de-koulikoro", "COMMUNE URBAINE DE KOULIKORO",
     "koulikoro-cercle"),
    ("daban", "DABAN", "kati"),
    ("dabia", "DABIA", "kenieba"),
    ("dabo", "DABO", "nara"),
    ("dah", "DAH", "san"),
    ("dallah", "DALLAH", "douentza"),
    ("danderesso", "DANDERESSO", "sikasso-cercle"),
    ("dandoli", "DANDOLI", "bandiagara"),
    ("dandougou-fakala", "DANDOUGOU FAKALA", "djenne"),
    ("dangha", "DANGHA", "dire"),
    ("dangol-bore", "DANGOL-BORE", "douentza"),
    ("danou", "DANOU", "bougouni"),
    ("debelin", "DEBELIN", "bougouni"),
    ("debere", "DEBERE", "douentza"),
    ("deboye", "DEBOYE", "youwarou"),
    ("defina", "DEFINA", "bougouni"),
    ("degnekoro", "DEGNEKORO", "dioila"),
    ("dembela", "DEMBELA", "sikasso-cercle"),
    ("derary", "DERARY", "djenne"),
    ("diabaly", "DIABALY", "niono"),
    ("diabigue", "DIABIGUE", "nioro"),
    ("diafarabe", "DIAFARABE", "tenenkou"),
    ("diafoumou-diongaga", "DIAFOUMOU DIONGAGA", "yelimane"),
    ("diafoumou-gory", "DIAFOUMOU GORY", "yelimane"),
    ("diago", "DIAGO", "kati"),
    ("diaka", "DIAKA", "tenenkou"),
    ("diakon", "DIAKON", "bafoulabe"),
    ("diakourouna", "DIAKOUROUNA", "san"),
    ("dialafara", "DIALAFARA", "kenieba"),
    ("dialakoro", "DIALAKORO", "sikasso-cercle"),
    ("dialakoroba", "DIALAKOROBA", "kati"),
    ("dialakorodji", "DIALAKORODJI", "kati"),
    ("diallan", "DIALLAN", "bafoulabe"),
    ("diallassagou", "DIALLASSAGOU", "bankass"),
    ("dialloube", "DIALLOUBE", "mopti-cercle"),
    ("diamnati", "DIAMNATI", "bandiagara"),
    ("diamou", "DIAMOU", "kayes-cercle"),
    ("diangounte-camara", "DIANGOUNTE CAMARA", "diema"),
    ("dianguirde", "DIANGUIRDE", "diema"),
    ("diankabou", "DIANKABOU", "koro"),
    ("dianke", "DIANKE", "niafunke"),
    ("dianvely", "DIANVELY", "douentza"),
    ("diaramana", "DIARAMANA", "bla"),
    ("diarra", "DIARRA", "nioro"),
    ("diaye-coura", "DIAYE COURA", "nioro"),
    ("diebe", "DIEBE", "dioila"),
    ("diedougou", "DIEDOUGOU", "dioila"),
    ("diedougou", "DIEDOUGOU", "kati"),
    ("diedougou", "DIEDOUGOU", "koutiala"),
    ("diedougou", "DIEDOUGOU", "segou-cercle"),
    ("dieli", "DIELI", "san"),
    ("diema", "DIEMA", "diema"),
    ("diena", "DIENA", "bla"),
    ("dieoura", "DIEOURA", "diema"),
    ("diganibougou", "DIGANIBOUGOU", "segou-cercle"),
    ("dilly", "DILLY", "nara"),
    ("dimbal-habbe", "DIMBAL HABBE", "bankass"),
    ("dinandougou", "DINANDOUGOU", "koulikoro-cercle"),
    ("dinangourou", "DINANGOUROU", "koro"),
    ("dindenko", "DINDENKO", "kita"),
    ("dio-gare", "DIO-GARE", "kati"),
    ("diokeli", "DIOKELI", "bafoulabe"),
    ("diomatene", "DIOMATENE", "sikasso-cercle"),
    ("diondori", "DIONDORI", "tenenkou"),
    ("diora", "DIORA", "tominian"),
    ("dioro", "DIORO", "segou-cercle"),
    ("diou", "DIOU", "kadiolo"),
    ("diouman", "DIOUMAN", "dioila"),
    ("dioumara-koussata", "DIOUMARA KOUSSATA", "diema"),
    ("dioumatene", "DIOUMATENE", "kadiolo"),
    ("diouna", "DIOUNA", "segou-cercle"),
    ("dioungani", "DIOUNGANI", "koro"),
    ("diouradougou-kafo", "DIOURADOUGOU KAFO", "koutiala"),
    ("dire", "DIRE", "dire"),
    ("dirma", "DIRMA", "youwarou"),
    ("djallon-foula", "DJALLON FOULA", "yanfolila"),
    ("djaptodji", "DJAPTODJI", "douentza"),
    ("djeguena", "DJEGUENA", "san"),
    ("djelebou", "DJELEBOU", "kayes-cercle"),
    ("djenne", "DJENNE", "djenne"),
    ("djidian", "DJIDIAN", "kita"),
    ("djidieni", "DJIDIENI", "kolokani"),
    ("djiguiya-de-koloni", "DJIGUIYA DE KOLONI", "yanfolila"),
    ("djougoun", "DJOUGOUN", "kita"),
    ("dogani-bere", "DOGANI BERE", "bandiagara"),
    ("dogo", "DOGO", "bougouni"),
    ("dogodouman", "DOGODOUMAN", "kati"),
    ("dogofry", "DOGOFRY", "nara"),
    ("dogofry", "DOGOFRY", "niono"),
    ("dogoni", "DOGONI", "sikasso-cercle"),
    ("dolendougou", "DOLENDOUGOU", "dioila"),
    ("domba", "DOMBA", "bougouni"),
    ("dombia", "DOMBIA", "kenieba"),
    ("dombila", "DOMBILA", "kati"),
    ("dongo", "DONGO", "youwarou"),
    ("doubabougou", "DOUBABOUGOU", "kati"),
    ("doucoumbo", "DOUCOUMBO", "bandiagara"),
    ("douekire", "DOUEKIRE", "goundam"),
    ("douentza", "DOUENTZA", "douentza"),
    ("dougabougou", "DOUGABOUGOU", "segou-cercle"),
    ("dougoufie", "DOUGOUFIE", "baraoueli"),
    ("dougouolo", "DOUGOUOLO", "bla"),
    ("dougoutene-i", "DOUGOUTENE I", "koro"),
    ("dougoutene-ii", "DOUGOUTENE II", "koro"),
    ("doukouria", "DOUKOURIA", "goundam"),
    ("doumanaba", "DOUMANABA", "sikasso-cercle"),
    ("doumba", "DOUMBA", "koulikoro-cercle"),
    ("dourou", "DOUROU", "bandiagara"),
    ("duguwolowula", "DUGUWOLOWULA", "banamba"),
    ("essakane", "ESSAKANE", "goundam"),
    ("essouk", "ESSOUK", "kidal-cercle"),
    ("fagui", "FAGUI", "koutiala"),
    ("fakala", "FAKALA", "djenne"),
    ("fakola", "FAKOLA", "kolondieba"),
    ("fakolo", "FAKOLO", "koutiala"),
    ("falea", "FALEA", "kenieba"),
    ("faleme", "FALEME", "kayes-cercle"),
    ("fallou", "FALLOU", "nara"),
    ("falo", "FALO", "bla"),
    ("fama", "FAMA", "sikasso-cercle"),
    ("fanga", "FANGA", "yelimane"),
    ("fangasso", "FANGASSO", "tominian"),
    ("fani", "FANI", "bla"),
    ("faraba", "FARABA", "kati"),
    ("faraba", "FARABA", "kenieba"),
    ("faradiele", "FARADIELE", "bougouni"),
    ("faragouaran", "FARAGOUARAN", "bougouni"),
    ("farakala", "FARAKALA", "sikasso-cercle"),
    ("farako", "FARAKO", "kolondieba"),
    ("farako", "FARAKO", "segou-cercle"),
    ("farakou-massa", "FARAKOU MASSA", "segou-cercle"),
    ("farimake", "FARIMAKE", "youwarou"),
    ("fassoudebe", "FASSOUDEBE", "diema"),
    ("fatao", "FATAO", "diema"),
    ("fatine", "FATINE", "segou-cercle"),
    ("fatine", "FATINE", "segou-cercle"),
    ("fatoma", "FATOMA", "mopti-cercle"),
    ("fegui", "FEGUI", "kayes-cercle"),
    ("femaye", "FEMAYE", "djenne"),
    ("finkolo", "FINKOLO", "sikasso-cercle"),
    ("finkolo-ganadougou", "FINKOLO GANADOUGOU", "sikasso-cercle"),
    ("fion", "FION", "san"),
    ("fittouga", "FITTOUGA", "niafunke"),
    ("folomana", "FOLOMANA", "macina"),
    ("fourou", "FOUROU", "kadiolo"),
    ("gabero", "GABERO", "gao-cercle"),
    ("gadougou-1", "GADOUGOU 1", "kita"),
    ("gadougou-2", "GADOUGOU 2", "kita"),
    ("gandamia", "GANDAMIA", "douentza"),
    ("garalo", "GARALO", "bougouni"),
    ("garbakoira", "GARBAKOIRA", "dire"),
    ("gargando", "GARGANDO", "goundam"),
    ("gavinane", "GAVINANE", "nioro"),
    ("gogui", "GOGUI", "nioro"),
    ("gomitradougou", "GOMITRADOUGOU", "diema"),
    ("gongasso", "GONGASSO", "sikasso-cercle"),
    ("gory", "GORY", "yelimane"),
    ("gory-gopela", "GORY GOPELA", "kayes-cercle"),
    ("gossi", "GOSSI", "gourma-rharous"),
    ("gouadji-kao", "GOUADJI KAO", "koutiala"),
    ("gouanan", "GOUANAN", "yanfolila"),
    ("gouandiaka", "GOUANDIAKA", "yanfolila"),
    ("goudie-sougouna", "GOUDIE SOUGOUNA", "koutiala"),
    ("gouendo", "GOUENDO", "baraoueli"),
    ("goumera", "GOUMERA", "kayes-cercle"),
    ("goundam", "GOUNDAM", "goundam"),
    ("gounfan", "GOUNFAN", "bafoulabe"),
    ("gounzoureye", "GOUNZOUREYE", "gao-cercle"),
    ("groumera", "GROUMERA", "diema"),
    ("guedebine", "GUEDEBINE", "diema"),
    ("guegneka", "GUEGNEKA", "dioila"),
    ("guemoukouraba", "GUEMOUKOURABA", "kita"),
    ("guenegore", "GUENEGORE", "kenieba"),
    ("gueneibe", "GUENEIBE", "nara"),
    ("guidimakan-keri-kaffo", "GUIDIMAKAN KERI KAFFO", "kayes-cercle"),
    ("guidime", "GUIDIME", "yelimane"),
    ("guihoyo", "GUIHOYO", "kolokani"),
    ("guire", "GUIRE", "nara"),
    ("haibongo", "HAIBONGO", "dire"),
    ("haire", "HAIRE", "douentza"),
    ("hamzakoma", "HAMZAKOMA", "gourma-rharous"),
    ("haribomo", "HARIBOMO", "gourma-rharous"),
    ("hawa-dembaya", "HAWA DEMBAYA", "kayes-cercle"),
    ("hombori", "HOMBORI", "douentza"),
    ("inadiatafane", "INADIATAFANE", "gourma-rharous"),
    ("inekar", "INEKAR", "menaka"),
    ("intadjedite", "INTADJEDITE", "tin-essako"),
    ("issa-bery", "ISSA BERY", "goundam"),
    ("jekafo", "JEKAFO", "dioila"),
    ("kabarasso", "KABARASSO", "sikasso-cercle"),
    ("kaboila", "KABOILA", "sikasso-cercle"),
    ("kadiaba-kadiel", "KADIABA KADIEL", "nioro"),
    ("kadiana", "KADIANA", "kolondieba"),
    ("kadiolo", "KADIOLO", "kadiolo"),
    ("kafo-faboli", "KAFO FABOLI", "koutiala"),
    ("kafouziela", "KAFOUZIELA", "sikasso-cercle"),
    ("kai", "KAI", "kadiolo"),
    ("kala-siguida", "KALA SIGUIDA", "niono"),
    ("kalabancoro", "KALABANCORO", "kati"),
    ("kaladougou", "KALADOUGOU", "dioila"),
    ("kalake", "KALAKE", "baraoueli"),
    ("kalifabougou", "KALIFABOUGOU", "kati"),
    ("kambila", "KAMBILA", "kati"),
    ("kaneye", "KANEYE", "goundam"),
    ("kani-bonzon", "KANI BONZON", "bankass"),
    ("kaniegue", "KANIEGUE", "san"),
    ("kaniogo", "KANIOGO", "kangaba"),
    ("kapala", "KAPALA", "koutiala"),
    ("kapala", "KAPALA", "sikasso-cercle"),
    ("kapolondougou", "KAPOLONDOUGOU", "sikasso-cercle"),
    ("karaba", "KARABA", "san"),
    ("karakoro", "KARAKORO", "kayes-cercle"),
    ("karan", "KARAN", "kangaba"),
    ("karangana", "KARANGANA", "yorosso"),
    ("karangouana-malle", "KARANGOUANA MALLE", "koutiala"),
    ("kareri", "KARERI", "tenenkou"),
    ("kassa", "KASSA", "koro"),
    ("kassama", "KASSAMA", "kenieba"),
    ("kassaro", "KASSARO", "kita"),
    ("kassorola", "KASSOROLA", "san"),
    ("katiena", "KATIENA", "segou-cercle"),
    ("kava", "KAVA", "san"),
    ("kayes-commune", "KAYES COMMUNE", "kayes-cercle"),
    ("kazangasso", "KAZANGASSO", "bla"),
    ("kebila", "KEBILA", "kolondieba"),
    ("keleya", "KELEYA", "bougouni"),
    ("kemekafo", "KEMEKAFO", "dioila"),
    ("kemene-tambo", "KEMENE TAMBO", "kayes-cercle"),
    ("kemeni", "KEMENI", "bla"),
    ("kende", "KENDE", "bandiagara"),
    ("kendie", "KENDIE", "bandiagara"),
    ("kenieba", "KENIEBA", "kenieba"),
    ("kerela", "KERELA", "dioila"),
    ("kerena", "KERENA", "douentza"),
    ("kewa", "KEWA", "djenne"),
    ("khouloum", "KHOULOUM", "kayes-cercle"),
    ("kiban", "KIBAN", "banamba"),
    ("kidal", "KIDAL", "kidal-cercle"),
    ("kiffosso-1", "KIFFOSSO 1", "yorosso"),
    ("kignan", "KIGNAN", "sikasso-cercle"),
    ("kilidougou", "KILIDOUGOU", "dioila"),
    ("kirane-kaniaga", "KIRANE KANIAGA", "yelimane"),
    ("kirchamba", "KIRCHAMBA", "dire"),
    ("kita-nord", "KITA NORD", "kita"),
    ("kita-ouest", "KITA OUEST", "kita"),
    ("klela", "KLELA", "sikasso-cercle"),
    ("kobri", "KOBRI", "kita"),
    ("kofan", "KOFAN", "sikasso-cercle"),
    ("kokele", "KOKELE", "bougouni"),
    ("kokofata", "KOKOFATA", "kita"),
    ("kokry", "KOKRY", "macina"),
    ("kola", "KOLA", "bougouni"),
    ("kolokani", "KOLOKANI", "kolokani"),
    ("kolokoba", "KOLOKOBA", "sikasso-cercle"),
    ("kolondieba", "KOLONDIEBA", "kolondieba"),
    ("kolongo", "KOLONGO", "macina"),
    ("kolonigue", "KOLONIGUE", "koutiala"),
    ("kolosso", "KOLOSSO", "kolondieba"),
    ("kondi", "KONDI", "dire"),
    ("konigue", "KONIGUE", "koutiala"),
    ("konina", "KONINA", "koutiala"),
    ("konna", "KONNA", "mopti-cercle"),
    ("konobougou", "KONOBOUGOU", "baraoueli"),
    ("konodimini", "KONODIMINI", "segou-cercle"),
    ("konseguela", "KONSEGUELA", "koutiala"),
    ("konsiga", "KONSIGA", "yelimane"),
    ("kontela", "KONTELA", "bafoulabe"),
    ("koporo-pen", "KOPORO PEN", "koro"),
    ("koporokendie-na", "KOPOROKENDIE NA", "koro"),
    ("korarou", "KORAROU", "douentza"),
    ("korera-kore", "KORERA KORE", "nioro"),
    ("koro", "KORO", "koro"),
    ("korodougou", "KORODOUGOU", "bla"),
    ("korombana", "KOROMBANA", "mopti-cercle"),
    ("koromo", "KOROMO", "koutiala"),
    ("koronga", "KORONGA", "nara"),
    ("kotouba", "KOTOUBA", "kita"),
    ("koubaye", "KOUBAYE", "mopti-cercle"),
    ("koubelwel-koundia", "KOUBELWEL KOUNDIA", "douentza"),
    ("koula", "KOULA", "koulikoro-cercle"),
    ("koula", "KOULA", "tominian"),
    ("koulandougou", "KOULANDOUGOU", "bla"),
    ("koulogon-habbe", "KOULOGON HABBE", "bankass"),
    ("koulou", "KOULOU", "kita"),
    ("koumaira", "KOUMAIRA", "niafunke"),
    ("koumankou", "KOUMANKOU", "sikasso-cercle"),
    ("koumantou", "KOUMANTOU", "bougouni"),
    ("koumbia", "KOUMBIA", "yorosso"),
    ("kounari", "KOUNARI", "mopti-cercle"),
    ("koundian", "KOUNDIAN", "bafoulabe"),
    ("kouniakary", "KOUNIAKARY", "kayes-cercle"),
    ("kouniana", "KOUNIANA", "koutiala"),
    ("kouoro", "KOUORO", "sikasso-cercle"),
    ("kourouba", "KOUROUBA", "kati"),
    ("kouroukoto", "KOUROUKOTO", "kenieba"),
    ("kouroulamini", "KOUROULAMINI", "bougouni"),
    ("kourouma", "KOUROUMA", "sikasso-cercle"),
    ("kourounnikoto", "KOUROUNNIKOTO", "kita"),
    ("koury", "KOURY", "yorosso"),
    ("koussan", "KOUSSAN", "yanfolila"),
    ("koussane", "KOUSSANE", "kayes-cercle"),
    ("kremis", "KREMIS", "yelimane"),
    ("lafia", "LAFIA", "tombouctou-cercle"),
    ("lakamane", "LAKAMANE", "diema"),
    ("lambidou", "LAMBIDOU", "diema"),
    ("lanfiala", "LANFIALA", "tominian"),
    ("lere", "LERE", "niafunke"),
    ("lessagou-habbe", "LESSAGOU HABBE", "bankass"),
    ("liberte-dembaya", "LIBERTE DEMBAYA", "kayes-cercle"),
    ("lobougoula", "LOBOUGOULA", "sikasso-cercle"),
    ("logo", "LOGO", "kayes-cercle"),
    ("logouana", "LOGOUANA", "koutiala"),
    ("loulouni", "LOULOUNI", "kadiolo"),
    ("lowol-gueou", "LOWOL GUEOU", "bandiagara"),
    ("macina", "MACINA", "macina"),
    ("madiama", "MADIAMA", "djenne"),
    ("madiga-sacko", "MADIGA-SACKO", "diema"),
    ("madina", "MADINA", "kita"),
    ("madina-sacko", "MADINA SACKO", "banamba"),
    ("madougou", "MADOUGOU", "koro"),
    ("mafoune", "MAFOUNE", "tominian"),
    ("mahina", "MAHINA", "bafoulabe"),
    ("mahou", "MAHOU", "yorosso"),
    ("makano", "MAKANO", "kita"),
    ("mande", "MANDE", "kati"),
    ("mandiakuy", "MANDIAKUY", "tominian"),
    ("maramandougou", "MARAMANDOUGOU", "kangaba"),
    ("marekhaffo", "MAREKHAFFO", "yelimane"),
    ("marena-diombougou", "MARENA DIOMBOUGOU", "kayes-cercle"),
    ("mariko", "MARIKO", "niono"),
    ("marintoumania", "MARINTOUMANIA", "kayes-cercle"),
    ("markala", "MARKALA", "segou-cercle"),
    ("massala", "MASSALA", "segou-cercle"),
    ("massantola", "MASSANTOLA", "kolokani"),
    ("massigui", "MASSIGUI", "dioila"),
    ("matomo", "MATOMO", "macina"),
    ("mbouna", "M'BOUNA", "goundam"),
    ("meguetan", "MEGUETAN", "koulikoro-cercle"),
    ("mena", "MENA", "kolondieba"),
    ("menaka", "MENAKA", "menaka"),
    ("menamba-1", "MENAMBA 1", "yorosso"),
    ("meridiela", "MERIDIELA", "bougouni"),
    ("meridiela", "MERIDIELA", "bougouni"),
    ("metoumou", "METOUMOU", "bandiagara"),
    ("miena", "MIENA", "koutiala"),
    ("minidian", "MINIDIAN", "kangaba"),
    ("miniko", "MINIKO", "sikasso-cercle"),
    ("miria", "MIRIA", "sikasso-cercle"),
    ("misseni", "MISSENI", "kadiolo"),
    ("missirikoro", "MISSIRIKORO", "sikasso-cercle"),
    ("mondoro", "MONDORO", "douentza"),
    ("moribabougou", "MORIBABOUGOU", "kati"),
    ("moribila", "MORIBILA", "san"),
    ("mountougoula", "MOUNTOUGOULA", "kati"),
    ("mpessoba", "M'PESSOBA", "koutiala"),
    ("nafanga", "NAFANGA", "koutiala"),
    ("namala-guimba", "NAMALA GUIMBA", "kita"),
    ("nampalari", "NAMPALARI", "niono"),
    ("nampe", "NAMPE", "koutiala"),
    ("nangalasso", "NANGALASSO", "kolondieba"),
    ("nangola", "NANGOLA", "dioila"),
    ("nara", "NARA", "nara"),
    ("narena", "NARENA", "kangaba"),
    ("natien", "NATIEN", "sikasso-cercle"),
    ("ndlondougou", "N'DLONDOUGOU", "dioila"),
    ("ndodjiga", "N'DODJIGA", "youwarou"),
    ("nema-badeya-kafo", "NEMA-BADEYA-KAFO", "djenne"),
    ("ngabacoro-droit", "NGABACORO DROIT", "kati"),
    ("ngara", "N'GARA", "segou-cercle"),
    ("ngaradougou", "N'GARADOUGOU", "dioila"),
    ("ngassola", "N'GASSOLA", "baraoueli"),
    ("ngoa", "N'GOA", "san"),
    ("ngolobougou", "N'GOLOBOUGOU", "dioila"),
    ("ngolodiana", "N'GOLODIANA", "kolondieba"),
    ("ngolonianasso", "N'GOLONIANASSO", "koutiala"),
    ("ngorkou", "N'GORKOU", "niafunke"),
    ("ngountjina", "N'GOUNTJINA", "koutiala"),
    ("ngouraba", "N'GOURABA", "kati"),
    ("niagadina", "NIAGADINA", "kati"),
    ("niala", "NIALA", "bla"),
    ("niamana", "NIAMANA", "nara"),
    ("niamana", "NIAMANA", "san"),
    ("niambia", "NIAMBIA", "bafoulabe"),
    ("niansanari", "NIANSANARI", "djenne"),
    ("niantaga", "NIANTAGA", "koutiala"),
    ("niantanso", "NIANTANSO", "kita"),
    ("niantjila", "NIANTJILA", "dioila"),
    ("niasso", "NIASSO", "san"),
    ("niena", "NIENA", "sikasso-cercle"),
    ("nimbougou", "NIMBOUGOU", "kadiolo"),
    ("niono", "NIONO", "niono"),
    ("nioro-tougoume-rangabe", "NIORO TOUGOUME RANGABE", "nioro"),
    ("nioumamakana", "NIOUMAMAKANA", "kati"),
    ("nkoumandougou", "N'KOUMANDOUGOU", "segou-cercle"),
    # ("non-encore-affecte", "NON ENCORE AFFECTE", "kati"),
    # ("non-encore-affecte", "NON ENCORE AFFECTE", "nioro"),
    # ("non-encore-affecte", "NON ENCORE AFFECTE", "youwarou"),
    ("nongo-souala", "NONGO-SOUALA", "sikasso-cercle"),
    ("nonimpebougou", "NONIMPEBOUGOU", "macina"),
    ("nonkon", "NONKON", "kolokani"),
    ("nonssombougou", "NONSSOMBOUGOU", "kolokani"),
    ("nouga", "NOUGA", "kangaba"),
    ("ntillit", "N'TILLIT", "gao-cercle"),
    ("ntjiba", "N'TJIBA", "kati"),
    ("ntjikouna", "N'TJIKOUNA", "sikasso-cercle"),
    ("ntorosso", "N'TOROSSO", "san"),
    ("ntossoni", "N'TOSSONI", "koutiala"),
    ("nyamina", "NYAMINA", "koulikoro-cercle"),
    ("ondougou", "ONDOUGOU", "bandiagara"),
    ("ouagadou", "OUAGADOU", "nara"),
    ("oualia", "OUALIA", "bafoulabe"),
    ("ouan", "OUAN", "tominian"),
    ("ouattagouna", "OUATTAGOUNA", "ansongo"),
    ("ouelessebougou", "OUELESSEBOUGOU", "kati"),
    ("ouenkoro", "OUENKORO", "bankass"),
    ("ouinerden", "OUINERDEN", "gourma-rharous"),
    ("ouolodo", "OUOLODO", "kolokani"),
    ("ouolon", "OUOLON", "san"),
    ("ourikela", "OURIKELA", "yorosso"),
    ("ouro-ali", "OURO ALI", "djenne"),
    ("ouro-ardo", "OURO ARDO", "tenenkou"),
    ("ouro-guire", "OURO-GUIRE", "tenenkou"),
    ("ouro-modi", "OURO-MODI", "mopti-cercle"),
    ("ouroube-doude", "OUROUBE DOUDE", "mopti-cercle"),
    ("ouroun", "OUROUN", "bougouni"),
    ("pel-maoude", "PEL MAOUDE", "koro"),
    ("pelengana", "PELENGANA", "segou-cercle"),
    ("pelou", "PELOU", "bandiagara"),
    ("petaka", "PETAKA", "douentza"),
    ("pignari", "PIGNARI", "bandiagara"),
    ("pignari-bana", "PIGNARI BANA", "bandiagara"),
    ("pimperna", "PIMPERNA", "sikasso-cercle"),
    ("pogo", "POGO", "niono"),
    ("pondori", "PONDORI", "djenne"),
    ("razelma", "RAZELMA", "goundam"),
    ("rharous", "RHAROUS", "gourma-rharous"),
    ("saboula", "SABOULA", "kita"),
    ("sadiola", "SADIOLA", "kayes-cercle"),
    ("safo", "SAFO", "kati"),
    ("sagabala", "SAGABALA", "kolokani"),
    ("sagalo", "SAGALO", "kenieba"),
    ("sahel", "SAHEL", "kayes-cercle"),
    ("sakoiba", "SAKOIBA", "segou-cercle"),
    ("salam", "SALAM", "tombouctou-cercle"),
    ("saloba", "SALOBA", "macina"),
    ("sama-foulala", "SAMA FOULALA", "segou-cercle"),
    ("samabogo", "SAMABOGO", "bla"),
    ("same-diongoma", "SAME DIONGOMA", "kayes-cercle"),
    ("samine", "SAMINE", "segou-cercle"),
    ("sana", "SANA", "macina"),
    ("sanando", "SANANDO", "baraoueli"),
    ("sanankoro-djitoumou", "SANANKORO DJITOUMOU", "kati"),
    ("sanankoroba", "SANANKOROBA", "kati"),
    ("sandare", "SANDARE", "nioro"),
    ("sanekuy", "SANEKUY", "tominian"),
    ("sangarebougou", "SANGAREBOUGOU", "kati"),
    ("sangha", "SANGHA", "bandiagara"),
    ("sankarani", "SANKARANI", "yanfolila"),
    ("sansanding", "SANSANDING", "segou-cercle"),
    ("sansankide", "SANSANKIDE", "diema"),
    ("sanso", "SANSO", "bougouni"),
    ("sanzana", "SANZANA", "sikasso-cercle"),
    ("sareyamou", "SAREYAMOU", "dire"),
    ("sasalbe", "SASALBE", "mopti-cercle"),
    ("sebekoro", "SEBEKORO", "kita"),
    ("sebekoro-1", "SEBEKORO 1", "kolokani"),
    ("sebete", "SEBETE", "banamba"),
    ("sebougou", "SEBOUGOU", "segou-cercle"),
    ("sefeto-nord", "SEFETO NORD", "kita"),
    ("sefeto-ouest", "SEFETO OUEST", "kita"),
    ("segala", "SEGALA", "kayes-cercle"),
    ("segue", "SEGUE", "bankass"),
    ("segue-ire", "SEGUE IRE", "bandiagara"),
    ("selefougou", "SELEFOUGOU", "kangaba"),
    ("senko", "SENKO", "kita"),
    ("sere-moussa-ani-samou-de-siekorole",
     "SERE MOUSSA ANI SAMOU DE SIEKOROLE", "yanfolila"),
    ("serere", "SERERE", "gourma-rharous"),
    ("sero-diamanou", "SERO DIAMANOU", "kayes-cercle"),
    ("siadougou", "SIADOUGOU", "san"),
    ("sibila", "SIBILA", "segou-cercle"),
    ("sibirila", "SIBIRILA", "bougouni"),
    ("siby", "SIBY", "kati"),
    ("sidibela", "SIDIBELA", "bafoulabe"),
    ("sido", "SIDO", "bougouni"),
    ("simbi", "SIMBI", "nioro"),
    ("simbi", "SIMBI", "nioro"),
    ("sincina", "SINCINA", "koutiala"),
    ("sinkolo", "SINKOLO", "koutiala"),
    ("sio", "SIO", "mopti-cercle"),
    ("sirakoro", "SIRAKORO", "kita"),
    ("sirakorola", "SIRAKOROLA", "koulikoro-cercle"),
    ("siribala", "SIRIBALA", "niono"),
    ("sirifila-boundy", "SIRIFILA BOUNDY", "niono"),
    ("sitakily", "SITAKILY", "kenieba"),
    ("soboundou", "SOBOUNDOU", "niafunke"),
    ("sobra", "SOBRA", "kati"),
    ("socoura", "SOCOURA", "mopti-cercle"),
    ("soignebougou", "SOIGNEBOUGOU", "segou-cercle"),
    ("sokolo", "SOKOLO", "niono"),
    ("sokoura", "SOKOURA", "bankass"),
    ("sokourani-missirikoro", "SOKOURANI-MISSIRIKORO", "sikasso-cercle"),
    ("somankidi", "SOMANKIDI", "kayes-cercle"),
    ("somasso", "SOMASSO", "bla"),
    ("somo", "SOMO", "baraoueli"),
    ("somo", "SOMO", "san"),
    ("songo-doubakore", "SONGO DOUBAKORE", "koutiala"),
    ("songoua", "SONGOUA", "koutiala"),
    ("soni-ali-ber", "SONI ALI BER", "gao-cercle"),
    ("sony", "SONY", "kayes-cercle"),
    ("sorobasso", "SOROBASSO", "koutiala"),
    ("soroly", "SOROLY", "bandiagara"),
    ("souba", "SOUBA", "segou-cercle"),
    ("soubala", "SOUBALA", "bankass"),
    ("sougoulbe", "SOUGOULBE", "tenenkou"),
    ("souleye", "SOULEYE", "macina"),
    ("soumpi", "SOUMPI", "niafunke"),
    ("soumpou", "SOUMPOU", "yelimane"),
    ("souransan-tomoto", "SOURANSAN-TOMOTO", "kita"),
    ("sourountouna", "SOUROUNTOUNA", "san"),
    ("soye", "SOYE", "mopti-cercle"),
    ("sy", "SY", "san"),
    ("syen-toula", "SYEN TOULA", "bougouni"),
    ("taboye", "TABOYE", "bourem"),
    ("tafassirga", "TAFASSIRGA", "kayes-cercle"),
    ("tagandougou", "TAGANDOUGOU", "yanfolila"),
    ("talataye", "TALATAYE", "ansongo"),
    ("tamani", "TAMANI", "baraoueli"),
    ("tambaga", "TAMBAGA", "kita"),
    ("tao", "TAO", "koutiala"),
    ("tarkint", "TARKINT", "bourem"),
    ("tedie", "TEDIE", "douentza"),
    ("teimala-banimonotie", "TEIMALA BANIMONOTIE", "bougouni"),
    ("tele", "TELE", "goundam"),
    ("tella", "TELLA", "sikasso-cercle"),
    ("temera", "TEMERA", "bourem"),
    ("tene", "TENE", "san"),
    ("teneni", "TENENI", "san"),
    ("tenenkou", "TENENKOU", "tenenkou"),
    ("tenindougou", "TENINDOUGOU", "dioila"),
    ("tessalit", "TESSALIT", "tessalit"),
    ("tesserela", "TESSERELA", "baraoueli"),
    ("tessit", "TESSIT", "ansongo"),
    ("tiakadougou-dialakoro", "TIAKADOUGOU DIALAKORO", "kati"),
    ("tiankadi", "TIANKADI", "sikasso-cercle"),
    ("tidermene", "TIDERMENE", "menaka"),
    ("tiele", "TIELE", "kati"),
    ("tiemena", "TIEMENA", "bla"),
    ("tienfala", "TIENFALA", "koulikoro-cercle"),
    ("tienkour", "TIENKOUR", "dire"),
    ("tilemsi", "TILEMSI", "gao-cercle"),
    ("tilemsi", "TILEMSI", "goundam"),
    ("timiri", "TIMIRI", "bandiagara"),
    ("timissa", "TIMISSA", "tominian"),
    ("timtaghene", "TIMTAGHENE", "tessalit"),
    ("tin-aicha", "TIN-AICHA", "goundam"),
    ("tin-essako", "TIN-ESSAKO", "tin-essako"),
    ("tin-hama", "TIN HAMA", "ansongo"),
    ("tindirma", "TINDIRMA", "dire"),
    ("tinguereguif", "TINGUEREGUIF", "dire"),
    ("tinzawatene", "TINZAWATENE", "abeibara"),
    ("tiongui", "TIONGUI", "kolondieba"),
    ("tioribougou", "TIORIBOUGOU", "kolokani"),
    ("togoro-kotia", "TOGORO-KOTIA", "tenenkou"),
    ("togou", "TOGOU", "segou-cercle"),
    ("togue-mourari", "TOGUE MOURARI", "djenne"),
    ("toguere-coumbe", "TOGUERE-COUMBE", "tenenkou"),
    ("tominian", "TOMINIAN", "tominian"),
    ("tomora", "TOMORA", "bafoulabe"),
    ("tongue", "TONGUE", "macina"),
    ("tonka", "TONKA", "goundam"),
    ("tori", "TORI", "bankass"),
    ("toridaga-ko", "TORIDAGA-KO", "niono"),
    ("toubacoro", "TOUBACORO", "banamba"),
    ("tougouni", "TOUGOUNI", "koulikoro-cercle"),
    ("toukoroba", "TOUKOROBA", "banamba"),
    ("toukoto", "TOUKOTO", "kita"),
    ("touna", "TOUNA", "bla"),
    ("tourakolomba", "TOURAKOLOMBA", "san"),
    ("tousseguela", "TOUSSEGUELA", "kolondieba"),
    ("toya", "TOYA", "yelimane"),
    ("tringa", "TRINGA", "yelimane"),
    ("troungoumbe", "TROUNGOUMBE", "nioro"),
    ("wacoro", "WACORO", "dioila"),
    ("wadouba", "WADOUBA", "bandiagara"),
    ("waky", "WAKY", "san"),
    ("wassoulou-balle", "WASSOULOU BALLE", "yanfolila"),
    ("wateni", "WATENI", "sikasso-cercle"),
    ("wola", "WOLA", "bougouni"),
    ("yallankoro-soloba", "YALLANKORO SOLOBA", "yanfolila"),
    ("yangasso", "YANGASSO", "bla"),
    ("yasso", "YASSO", "tominian"),
    ("yelekebougou", "YELEKEBOUGOU", "kati"),
    ("yeredon-saniona", "YEREDON SANIONA", "niono"),
    ("yerere", "YERERE", "nioro"),
    ("yinindougou", "YININDOUGOU", "bougouni"),
    ("yiridougou", "YIRIDOUGOU", "bougouni"),
    ("yognogo", "YOGNOGO", "koutiala"),
    ("yoro", "YORO", "koro"),
    ("yorosso", "YOROSSO", "yorosso"),
    ("youdiou", "YOUDIOU", "koro"),
    ("youri", "YOURI", "nioro"),
    ("zan-coulibaly", "ZAN COULIBALY", "dioila"),
    ("zanferebougou", "ZANFEREBOUGOU", "sikasso-cercle"),
    ("zanfigue", "ZANFIGUE", "koutiala"),
    ("zangaradougou", "ZANGARADOUGOU", "sikasso-cercle"),
    ("zangasso", "ZANGASSO", "koutiala"),
    ("zaniena", "ZANIENA", "koutiala"),
    ("zaniena", "ZANIENA", "sikasso-cercle"),
    ("zantiebougou", "ZANTIEBOUGOU", "bougouni"),
    ("zebala", "ZEBALA", "koutiala"),
    ("zegoua", "ZEGOUA", "kadiolo"),
    ("youwarou", "YOUWAROU", "youwarou"),
]

oracom = [
    ("5215", "PIGNARI"),
    ("5216", "PIGNARI BANA"),
    ("5217", "SANGHA"),
    ("5218", "SEGUE IRE"),
    ("5219", "SOROLY"),
    ("5220", "TIMIRI"),  # "TIMNIRI"
    ("5221", "WADOUBA"),
    ("5301", "BANKASS"),
    ("5302", "BAYE"),
    ("5303", "DIALLASSAGOU"),
    ("5304", "DIMBAL HABBE"),
    ("5305", "KANI BONZON"),  # "KANI BONZONI"
    ("5306", "KOULOGON HABBE"),  # "KOULOGON HABE"
    ("5307", "LESSAGOU HABBE"),  # "LESSAGOU HABE"
    ("5308", "OUENKORO"),  # "OUONKORO"
    ("5309", "SEGUE "),
    ("5310", "SOKOURA"),
    ("5311", "SOUBALA"),
    ("5312", "TORI"),
    ("5401", "DJENNE"),
    ("5402", "DANDOUGOU FAKALA"),
    ("5403", "DERARY"),
    ("5404", "FAKALA"),
    ("5405", "FEMAYE"),
    ("5406", "KEWA"),
    ("5407", "MADIAMA"),
    ("5408", "NEMA-BADEYA-KAFO"),  # "NEMA BADENYAKAFO"
    ("5409", "NIANSANARI"),  # "NIANSANARIE"
    ("5410", "OURO ALI"),
    ("5411", "PONDORI"),
    ("5412", "TOGUE MOURARI"),
    ("5501", "DOUENTZA"),
    ("5502", "DALLAH"),
    ("5503", "DANGOL-BORE"),  # "DANGOL BORE"
    ("5504", "DEBERE"),
    ("5505", "DIANVELY"),  # "DIANWELY"
    ("5506", "DJAPTODJI"),
    ("5507", "GANDAMIA"),
    ("5508", "HAIRE"),
    ("5509", "HOMBORI"),
    ("5510", "KERENA"),
    ("5511", "KORAROU"),
    ("5512", "KOUBELWEL KOUNDIA"),  # "KOUBEWEL KOUNDIA"
    ("5513", "MONDORO"),
    ("5514", "PETAKA"),
    ("5515", "TEDIE"),
    ("5601", "KORO"),
    ("5602", "BAMBA"),
    ("5603", "BARAPIRELI"),
    ("5604", "BONDO"),
    ("5605", "DIANKABOU"),
    ("5606", "DINANGOUROU"),
    ("5607", "DIOUNGANI"),  # "DIOUGANI"
    ("5608", "DOUGOUTENE I"),
    ("5609", "DOUGOUTENE II"),
    ("5610", "KASSA"),
    ("5611", "KOPORO PEN"),
    ("5612", "KOPOROKENDIE NA"),
    ("5613", "MADOUGOU"),
    ("5614", "PEL MAOUDE"),
    ("5615", "YORO"),
    ("5616", "YOUDIOU"),
    ("5701", "TENENKOU"),
    ("5702", "DIAFARABE"),
    ("5703", "DIAKA"),
    ("5704", "DIONDORI"),
    ("5705", "KARERI"),
    ("5706", "OURO ARDO"),
    ("5707", "OURO-GUIRE"),  # "OURO GUIRE"
    ("5708", "SOUGOULBE"),
    ("5709", "TOGORO-KOTIA"),  # "TOGORO KOTIA"
    ("5710", "TOGUERE-COUMBE"),  # "TOGUERE COUMBE"
    ("5801", "YOUWAROU"),
    ("5802", "BIMBERE TAMA"),
    ("5803", "DEBOYE"),
    ("5804", "DIRMA"),
    ("5805", "DONGO"),
    ("5806", "FARIMAKE"),
    ("5807", "N'DODJIGA"),
    ("6101", "COMMUNE DE TOMBOUCTOU"),  # "TOMBOUCTOU"
    ("6102", "ALAFIA"),
    ("6103", "BER"),
    ("6104", "BOUREM INALY"),
    ("6105", "LAFIA"),
    ("6106", "SALAM"),
    ("6201", "DIRE"),
    ("1704", "DIAFOUMOU GORY"),  # "DIAFOUNOU GORY"
    ("1709", "KREMIS"),
    ("1713", "TRINGA"),
    ("2103", "DOUMBA"),
    ("2107", "SIRAKOROLA"),
    ("2202", "BENKADI"),  # "BENKADI FOUNIA"
    ("2208", "TOUBACORO"),
    ("2303", "BANCO"),
    ("2306", "DEGNEKORO"),
    ("2310", "DOLENDOUGOU"),
    ("2315", "KILIDOUGOU"),
    ("2320", "NANGOLA"),
    ("2323", "WACORO"),
    ("2403", "BALAN BAKANA"),  # "BALA BAKAMA"
    ("2408", "NARENA"),
    ("2501", "COMMUNE DE KATI"),  # "KATI"
    ("2504", "BOSSOFALA"),  # "BOSSOFOLA"
    ("2508", "DIALAKOROBA"),
    ("2513", "DOMBILA"),
    ("2517", "KALIFABOUGOU"),
    ("2522", "MOUNTOUGOULA"),
    ("2527", "NIOUMAMAKANA"),
    ("2532", "SANGAREBOUGOU"),
    ("2537", "YELEKEBOUGOU"),
    ("4204", "GOUENDO"),
    ("4208", "SANANDO"),
    ("4301", "BLA"),
    ("4304", "DIENA"),
    ("4307", "FANI"),
    ("4310", "KORODOUGOU"),
    ("4314", "SOMASSO"),
    ("4401", "MACINA"),
    ("4405", "KOLONGO"),
    ("4408", "SALOBA"),
    ("4501", "NIONO"),
    ("4504", "KALA SIGUIDA"),
    ("4509", "SIRIFILA BOUNDY"),
    ("4603", "DAH"),
    ("4606", "DJEGUENA"),
    ("4610", "KASSOROLA"),
    ("4614", "N'TOROSSO"),
    ("4618", "SIADOUGOU"),
    ("4622", "TENE"),
    ("4625", "WAKY"),  # "WAKI"
    ("4703", "DIORA"),
    ("4707", "MAFOUNE"),
    ("4710", "SANEKUY"),
    ("5102", "BASSIROU"),
    ("5106", "KONNA"),
    ("5109", "KOUNARI"),
    ("5113", "SIO"),
    ("5201", "BANDIAGARA"),
    ("5205", "DIAMNATI"),
    ("5209", "KENDE"),
    ("5213", "ONDOUGOU"),
    ("1", "LOCALITE NON DEFINIE"),
    ("6202", "ARHAM"),
    ("6203", "BINGA"),
    ("6204", "BOUREM SIDI AMAR"),
    ("6205", "DANGHA"),
    ("6206", "GARBAKOIRA"),
    ("6207", "HAIBONGO"),
    ("6208", "KIRCHAMBA"),
    ("6209", "KONDI"),
    ("6210", "SAREYAMOU"),
    ("6211", "TIENKOUR"),
    ("6212", "TINDIRMA"),
    ("6213", "TINGUEREGUIF"),
    ("6301", "GOUNDAM"),
    ("6302", "ALZOUNOUB"),
    ("6303", "BINTAGOUNGOU"),
    ("6304", "ADARMALANE"),  # D'ADARMALANE"
    ("6305", "DOUEKIRE"),
    ("6306", "DOUKOURIA"),
    ("6307", "ESSAKANE"),
    ("6308", "GARGANDO"),
    ("6309", "ISSA BERY"),
    ("6310", "KANEYE"),
    ("6311", "M'BOUNA"),
    ("6312", "RAZELMA"),  # "RAZ EL MA"
    ("6313", "TELE"),
    ("6314", "TILEMSI"),
    ("6315", "TIN-AICHA"),  # "TIN AICHA"
    ("6316", "TONKA"),
    ("6401", "RHAROUS"),
    ("6402", "BAMBARA MAOUDE"),
    ("6403", "BANIKANE"),
    ("6404", "GOSSI"),
    ("6405", "HAMZAKOMA"),  # "HANZAKOMA"
    ("6406", "HARIBOMO"),
    ("6407", "INADIATAFANE"),
    ("6408", "OUINERDEN"),
    ("6409", "SERERE"),
    ("6501", "SOBOUNDOU"),
    ("6502", "BANIKANE NARHAWA"),
    ("6503", "DIANKE"),
    ("6504", "FITTOUGA"),
    ("6505", "KOUMAIRA"),
    ("6506", "LERE"),
    ("6507", "N'GORKOU"),
    ("6508", "SOUMPI"),
    ("7101", "COMMUNE DE GAO"),  # "GAO"
    ("7102", "ANCHAWADI"),
    ("7103", "GABERO"),
    ("7104", "GOUNZOUREYE"),
    ("7105", "N'TILLIT"),
    ("7106", "SONI ALI BER"),  # "SONY ALIBER"
    ("7107", "TILEMSI"),
    ("7201", "ANSONGO"),
    ("7202", "BARA"),
    ("7203", "BOURRA"),
    ("7204", "OUATTAGOUNA"),
    ("7205", "TALATAYE"),
    ("7206", "TESSIT"),
    ("7207", "TIN HAMA"),
    ("7301", "BOUREM"),
    ("7302", "BAMBA"),
    ("7303", "TABOYE"),
    ("7304", "TARKINT"),
    ("7305", "TEMERA"),
    ("7401", "MENAKA"),
    ("7402", "ALATA"),
    ("7403", "ANDERAMBOUKANE"),
    ("7404", "INEKAR"),
    ("7405", "TIDERMENE"),
    ("8101", "KIDAL"),
    ("8102", "ANEFIF"),
    ("8103", "ESSOUK"),
    ("8201", "ABEIBARA"),
    ("8202", "BOGHASSA"),
    ("8203", "TINZAWATENE"),
    ("8301", "TESSALIT"),
    ("8302", "ADJELHOC"),
    ("8303", "TIMTAGHENE"),
    ("8401", "TIN-ESSAKO"),  # "TIN ESSAKO"
    ("8402", "INTADJEDITE"),
    ("9101", "COMMUNE 1"),
    ("9102", "COMMUNE 2"),
    ("9103", "COMMUNE 3"),
    ("9104", "COMMUNE 4"),
    ("9105", "COMMUNE 5"),
    ("9106", "COMMUNE 6"),
    ("1101", "KAYES COMMUNE"),  # "KAYES"
    ("1102", "BANGASSI"),
    ("1103", "COLOMBINE"),  # "COLIMBINE"
    ("1104", "DIAMOU"),
    ("1105", "DJELEBOU"),
    ("1106", "FALEME"),
    ("1107", "FEGUI"),
    ("1108", "GORY GOPELA"),
    ("1109", "GOUMERA"),
    ("1110", "GUIDIMAKAN KERI KAFFO"),  # "GUIDIMAKAN KERI KAFF"
    ("1111", "HAWA DEMBAYA"),  # "HAWA DE MBAYA"
    ("1112", "KARAKORO"),
    ("1113", "KEMENE TAMBO"),
    ("1114", "KHOULOUM"),
    ("1115", "KOUNIAKARY"),
    ("1116", "KOUSSANE"),
    ("1117", "LIBERTE DEMBAYA"),  # "LIBERTE DE MBAYA"
    ("1118", "LOGO"),
    ("1119", "MARENA DIOMBOUGOU"),
    ("1120", "MARINTOUMANIA"),  # "MARITOUMANIA"
    ("1121", "SADIOLA"),
    ("1122", "SAHEL"),
    ("1123", "SAME DIONGOMA"),  # "SAME DIOMGOMA"
    ("1124", "SEGALA"),
    ("1125", "SERO DIAMANOU"),
    ("1126", "SOMANKIDI"),  # "SOMANKIDY"
    ("1127", "SONY"),
    ("1128", "TAFASSIRGA"),  # "TAFACIRGA"
    ("1201", "BAFOULABE                       "),
    ("1202", "BAMAFELE"),
    ("1203", "DIAKON"),
    ("1204", "DIALLAN"),
    ("1205", "DIOKELI"),
    ("1206", "GOUNFAN"),
    ("1207", "KONTELA"),
    ("1208", "KOUNDIAN"),
    ("1209", "MAHINA"),
    ("1301", "DIEMA"),
    ("1302", "BEMA"),
    ("1303", "DIANGOUNTE CAMARA"),
    ("1304", "DIANGUIRDE"),
    ("1305", "DIEOURA"),
    ("1306", "DIOUMARA KOUSSATA"),
    ("1307", "FASSOUDEBE"),
    ("1308", "FATAO"),
    ("1309", "GOMITRADOUGOU"),
    ("1310", "GROUMERA"),
    ("1311", "GUEDEBINE"),
    ("1312", "LAKAMANE"),
    ("1313", "LAMBIDOU"),
    ("1314", "MADIGA-SACKO"),  # "MADIGA SACKO"
    ("1315", "SANSANKIDE"),
    ("1401", "KENIEBA"),
    ("1402", "BAYE"),
    ("1403", "DABIA"),
    ("1404", "DIALAFARA"),
    ("1405", "DOMBIA"),
    ("1406", "FALEA"),
    ("1407", "FARABA"),
    ("1408", "GUENEGORE"),
    ("1409", "KASSAMA"),
    ("1410", "KOUROUKOTO"),  # "KROUKOTO"
    ("1411", "SAGALO"),
    ("1412", "SITAKILY"),  # "SITAKILLY"
    ("1501", "COMMUNE DE KITA"),  # "KITA"
    ("1502", "BADIA"),
    ("1503", "BENDOUGOUBA"),
    ("1504", "BENKADI FOUNIA"),
    ("1505", "BOUDOFO"),
    ("1506", "BOUGARIBAYA"),
    ("1507", "DINDENKO"),  # "DIDENKO"
    ("1508", "DJIDIAN"),
    ("1509", "DJOUGOUN"),
    ("1510", "GADOUGOU 1"),
    ("1511", "GADOUGOU 2"),
    ("1512", "GUEMOUKOURABA"),
    ("1513", "KASSARO"),
    ("1514", "KITA NORD"),
    ("1515", "KITA OUEST"),
    ("1516", "KOBRI"),
    ("1517", "KOKOFATA"),
    ("1518", "KOTOUBA"),
    ("1519", "KOULOU"),
    ("1520", "KOUROUNNIKOTO"),  # "KOUROUNINKOTO"
    ("1521", "MADINA"),
    ("1522", "MAKANO"),
    ("1523", "NAMALA GUIMBA"),
    ("1524", "NIANTANSO"),
    ("1525", "SABOULA"),
    ("1526", "SEBEKORO"),
    ("1527", "SEFETO NORD"),
    ("1528", "SEFETO OUEST"),
    ("1529", "SENKO"),
    ("1530", "SIRAKORO"),
    ("1531", "SOURANSAN-TOMOTO"),  # "SOURANSAN TOMOTO"
    ("1532", "TAMBAGA"),
    ("1533", "TOUKOTO"),
    ("1601", "COMMUNE DE NIORO"),  # "NIORO"
    ("1602", "BANIERE KORE"),
    ("1603", "DIABIGUE"),
    ("1604", "DIARRA"),
    ("1605", "DIAYE COURA"),
    ("1606", "GAVINANE"),
    ("1607", "GOGUI"),
    ("1608", "GUETEMA"),
    ("1609", "KADIABA KADIEL"),
    ("1610", "KORERA KORE"),  # "KOREKA KORE"
    ("1611", "NIORO TOUGOUME RANGABE"),  # "NIORO TOUGOUNE RANC"
    ("1612", "SANDARE"),
    ("1613", "SIMBI"),
    ("1614", "TROUNGOUMBE"),  # "TROUGOUMBE"
    ("1615", "YERERE"),
    ("1616", "YOURI"),
    ("1701", "YELIMANE"),
    ("1702", "GUIDIME"),
    ("1703", "DIAFOUMOU DIONGAGA"),  # "DIAFOUNOU DIONGAGA"
    ("1705", "FANGA"),
    ("1706", "GORY"),  # "GORY GOPELA"
    ("1707", "KIRANE KANIAGA"),
    ("1708", "KONSIGA"),
    ("1710", "MAREKHAFFO"),  # "MAREKAFO"
    ("1711", "SOUMPOU"),
    ("1712", "TOYA"),
    ("2101", "COMMUNE URBAINE DE KOULIKORO"),  # "KOULIKORO"
    ("2102", "DINANDOUGOU"),
    ("2104", "KOULA"),
    ("2105", "MEGUETAN"),
    ("2106", "NYAMINA"),
    ("2108", "TIENFALA"),
    ("2109", "TOUGOUNI"),
    ("2201", "BANAMBA"),
    ("2203", "BORON"),
    ("2204", "DUGUWOLOWULA"),
    ("2205", "KIBAN"),
    ("2206", "MADINA SACKO"),
    ("2207", "SEBETE"),
    ("2209", "TOUKOROBA"),
    ("2301", "DIOILA"),
    ("2302", "KALADOUGOU"),
    ("2304", "BENKADI"),  # "BENKADI FOUNIA"
    ("2305", "BINKO"),
    ("2307", "DIEBE"),
    ("2308", "DIEDOUGOU"),
    ("2309", "DIOUMAN"),
    ("2311", "GUEGNEKA"),
    ("2312", "JEKAFO"),
    ("2313", "KEMEKAFO"),
    ("2314", "KERELA"),
    ("2316", "MASSIGUI"),
    ("2317", "N'DLONDOUGOU"),
    ("2318", "N'GARADOUGOU"),
    ("2319", "N'GOLOBOUGOU"),
    ("2321", "NIANTJILA"),
    ("2322", "TENINDOUGOU"),
    ("2324", "ZAN COULIBALY"),
    ("2401", "KANGABA"),
    ("2402", "MINIDIAN"),
    ("2404", "BENKADI "),
    ("2405", "KANIOGO"),
    ("2406", "KARAN"),
    ("2407", "MARAMANDOUGOU"),
    ("2409", "NOUGA"),
    ("2410", "SELEFOUGOU"),
    ("2502", "BAGUINEDA CAMP"),
    ("2503", "BANCOUMANA"),
    ("2505", "BOUGOULA"),
    ("2506", "DABAN"),
    ("2507", "DIAGO"),
    ("2509", "DIALAKORODJI"),
    ("2510", "DIEDOUGOU"),
    ("2511", "DIO-GARE"),  # "DIO GARE"
    ("2512", "DOGODOUMAN"),
    ("2514", "DOUBABOUGOU"),
    ("2515", "FARABA"),
    ("2516", "KALABANCORO"),
    ("2518", "KAMBILA"),
    ("2519", "KOUROUBA"),
    ("2520", "MANDE"),
    ("2521", "MORIBABOUGOU"),
    ("2523", "NGABACORO DROIT"),  # "N'GABACORO"
    ("2524", "N'GOURABA"),
    ("2525", "N'TJIBA"),
    ("2526", "NIAGADINA"),
    ("2528", "OUELESSEBOUGOU"),
    ("2529", "SAFO"),
    ("2530", "SANANKORO DJITOUMOU"),
    ("2531", "SANANKOROBA"),
    ("2533", "SIBY"),
    ("2534", "SOBRA"),
    ("2535", "TIAKADOUGOU DIALAKORO"),  # "TIAKADOUGOUDIALAKO"
    ("2536", "TIELE"),
    ("2601", "KOLOKANI"),
    ("2602", "DJIDIENI"),  # "DIDIENI"
    ("2603", "GUIHOYO"),
    ("2604", "MASSANTOLA"),
    ("2605", "NONKON"),
    ("2606", "NONSSOMBOUGOU"),  # "NOSSOMBOUGOU"
    ("2607", "OUOLODO"),
    ("2608", "SAGABALA"),
    ("2609", "SEBEKORO 1"),  # "SEBECORO 1"
    ("2610", "TIORIBOUGOU"),
    ("2701", "NARA"),
    ("2702", "ALLAHINA"),
    ("2703", "DABO"),
    ("2704", "DILLY"),
    ("2705", "DOGOFRY"),
    ("2706", "FALLOU"),
    ("2707", "GUENEIBE"),
    ("2708", "GUIRE"),
    ("2709", "KORONGA"),
    ("2710", "NIAMANA"),
    ("2711", "OUAGADOU"),
    ("3101", "COMMUNE DE SIKASSO"),  # "SIKASSO"
    ("3102", "BENKADI"),
    ("3103", "BLENDIO"),
    ("3104", "DANDERESSO"),
    ("3105", "DEMBELA"),
    ("3106", "DIALAKORO"),
    ("3107", "DIOMATENE"),
    ("3108", "DOGONI"),
    ("3109", "DOUMANABA"),
    ("3110", "FAMA"),
    ("3111", "FARAKALA"),
    ("3112", "FINKOLO"),
    ("3113", "FINKOLO GANADOUGOU"),
    ("3114", "GONGASSO"),
    ("3115", "KABARASSO"),
    ("3116", "KABOILA"),
    ("3117", "KAFOUZIELA"),
    ("3118", "KAPALA"),
    ("3119", "KAPOLONDOUGOU"),
    ("3120", "KIGNAN"),
    ("3121", "KLELA"),
    ("3122", "KOFAN"),
    ("3123", "KOLOKOBA"),
    ("3124", "KOUMANKOU"),
    ("3125", "KOUORO"),
    ("3126", "KOUROUMA"),
    ("3127", "LOBOUGOULA"),
    ("3128", "MINIKO"),
    ("3129", "MIRIA"),
    ("3130", "MISSIRIKORO"),
    ("3131", "N'TJIKOUNA"),
    ("3132", "NATIEN"),
    ("3133", "NIENA"),
    ("3134", "NONGO-SOUALA"),  # "NONGO SOUALA"
    ("3135", "PIMPERNA"),
    ("3136", "SANZANA"),
    ("3137", "SOKOURANI-MISSIRIKORO"),  # "SOKOURANIMISSIRIKORO"
    ("3138", "TELLA"),
    ("3139", "TIANKADI"),
    ("3140", "WATENI"),
    ("3141", "ZANFEREBOUGOU"),
    ("3142", "ZANGARADOUGOU"),
    ("3143", "ZANIENA"),
    ("3201", "COMMUNE DE BOUGOUNI"),  # "BOUGOUNI"
    ("3202", "BLADIE-TIEMALA"),  # "BLADIE TIEMALA"
    ("3203", "DANOU"),
    ("3204", "DEBELIN"),
    ("3205", "DEFINA"),
    ("3206", "DOGO"),
    ("3207", "DOMBA"),
    ("3208", "FARADIELE"),
    ("3209", "FARAGOUARAN"),
    ("3210", "GARALO"),
    ("3211", "KELEYA"),
    ("3212", "KOKELE"),
    ("3213", "KOLA"),
    ("3214", "KOUMANTOU"),
    ("3215", "KOUROULAMINI"),  # "KOUROULAMIINI"
    ("3216", "MERIDIELA"),
    ("3217", "OUROUN"),
    ("3218", "SANSO"),
    ("3219", "SIBIRILA"),
    ("3220", "SIDO"),
    ("3221", "SYEN TOULA"),
    ("3222", "TEIMALA BANIMONOTIE"),  # "TIEMALA BANIMOTIE"
    ("3223", "WOLA"),
    ("3224", "YININDOUGOU"),
    ("3225", "YIRIDOUGOU"),
    ("3226", "ZANTIEBOUGOU"),
    ("3301", "KADIOLO"),
    ("3302", "DIOU"),  # "DIOUMAN"
    ("3303", "DIOUMATENE"),
    ("3304", "FOUROU"),
    ("3305", "KAI"),
    ("3306", "LOULOUNI"),
    ("3307", "MISSENI"),
    ("3308", "NIMBOUGOU"),
    ("3309", "ZEGOUA"),
    ("3401", "KOLONDIEBA"),
    ("3402", "BOUGOULA"),
    ("3403", "FAKOLA"),
    ("3404", "FARAKO"),
    ("3405", "KADIANA"),
    ("3406", "KEBILA"),
    ("3407", "KOLOSSO"),
    ("3408", "MENA"),
    ("3409", "N'GOLODIANA"),
    ("3410", "NANGALASSO"),
    ("3411", "TIONGUI"),
    ("3412", "TOUSSEGUELA"),
    ("3501", "COMMUNE DE KOUTIALA"),  # "KOUTIALA"
    ("3502", "DIEDOUGOU"),
    ("3503", "DIOURADOUGOU KAFO"),
    ("3504", "FAGUI"),
    ("3505", "FAKOLO"),
    ("3506", "GOUADJI KAO"),
    ("3507", "GOUDIE SOUGOUNA"),  # "GOUADJIE SOUGOUNA"
    ("3508", "KAFO FABOLI"),
    ("3509", "KAPALA"),
    ("3510", "KARANGOUANA MALLE"),  # "KARAGOUANA MALLE"
    ("3511", "KOLONIGUE"),
    ("3512", "KONINA"),
    ("3513", "KONIGUE"),  # "KONINGUE"
    ("3514", "KONSEGUELA"),
    ("3515", "KOROMO"),
    ("3516", "KOUNIANA"),
    ("3517", "LOGOUANA"),
    ("3518", "M'PESSOBA"),
    ("3519", "MIENA"),
    ("3520", "N'GOLONIANASSO"),
    ("3521", "N'GOUNTJINA"),  # "N'GOUTJINA"
    ("3522", "N'TOSSONI"),
    ("3523", "NAFANGA"),
    ("3524", "NAMPE"),
    ("3525", "NIANTAGA"),
    ("3526", "SINCINA"),
    ("3527", "SINKOLO"),
    ("3528", "SONGO DOUBAKORE"),  # "SONGO DOUBACORE"
    ("3529", "SONGOUA"),
    ("3530", "SOROBASSO"),
    ("3531", "TAO"),
    ("3532", "YOGNOGO"),
    ("3533", "ZANFIGUE"),
    ("3534", "ZANGASSO"),  # "ZANKASSO"
    ("3535", "ZANIENA"),  # "ZANINA"
    ("3536", "ZEBALA"),
    ("3601", "YANFOLILA"),
    ("3602", "WASSOULOU BALLE"),
    ("3603", "BAYA"),
    ("3604", "BOLO FOUTA"),
    ("3605", "DJALLON FOULA"),  # "DJALLON FOUTA"
    ("3606", "DJIGUIYA DE KOLONI"),
    ("3607", "GOUANAN"),
    ("3608", "GOUANDIAKA"),
    ("3609", "KOUSSAN"),
    ("3610", "SANKARANI"),
    ("3611", "SERE MOUSSA ANI SAMOU DE SIEKOROLE"),  # "SERE MOUSSA ANI SAMO"
    ("3612", "TAGANDOUGOU"),
    ("3613", "YALLANKORO SOLOBA"),  # "YALLAKORO SOLOBA"
    ("3701", "YOROSSO"),
    ("3702", "BOURA"),
    ("3703", "KARANGANA"),
    ("3704", "KIFFOSSO 1"),
    ("3705", "KOUMBIA"),
    ("3706", "KOURY"),
    ("3707", "MAHOU"),
    ("3708", "MENAMBA 1"),
    ("3709", "OURIKELA"),
    ("4101", "COMMUNE DE SEGOU"),  # "SEGOU"
    ("4102", "BAGUINDADOUGOU"),
    ("4103", "BELLEN"),
    ("4104", "BOUSSIN"),
    ("4105", "CINZANA"),
    ("4106", "DIEDOUGOU"),
    ("4107", "DIGANIBOUGOU"),
    ("4108", "DIORO"),
    ("4109", "DIOUNA"),
    ("4110", "DOUGABOUGOU"),
    ("4111", "FARAKO"),
    ("4112", "FARAKOU MASSA"),
    ("4113", "FATINE"),
    ("4114", "KAMIANDOUGOU"),
    ("4115", "KATIENA"),
    ("4116", "KONODIMINI"),
    ("4117", "MARKALA"),
    ("4118", "MASSALA"),
    ("4119", "N'GARA"),  # "N'GARADOUGOU"
    ("4120", "N'KOUMANDOUGOU"),
    ("4121", "PELENGANA"),  # "PELEGANA"
    ("4122", "SAKOIBA"),
    ("4123", "SAMA FOULALA"),
    ("4124", "SAMINE"),
    ("4125", "SANSANDING"),
    ("4126", "SEBOUGOU"),
    ("4127", "SIBILA"),
    ("4128", "SOIGNEBOUGOU"),
    ("4129", "SOUBA"),
    ("4130", "TOGOU"),
    ("4201", "BARAOUELI"),  # "BAROUELI"
    ("4202", "BOIDIE"),
    ("4203", "DOUGOUFIE"),
    ("4205", "KALAKE"),
    ("4206", "KONOBOUGOU"),
    ("4207", "N'GASSOLA"),
    ("4209", "SOMO"),
    ("4210", "TAMANI"),
    ("4211", "TESSERELA"),  # "TESSERLA"
    ("4302", "BEGUENE"),
    ("4303", "DIARAMANA"),
    ("4305", "DOUGOUOLO"),
    ("4306", "FALO"),
    ("4308", "KAZANGASSO"),
    ("4309", "KEMENI"),
    ("4311", "KOULANDOUGOU"),
    ("4312", "NIALA"),
    ("4313", "SAMABOGO"),
    ("4315", "TIEMENA"),
    ("4316", "TOUNA"),
    ("4317", "YANGASSO"),
    ("4402", "BOKY WERE"),
    ("4403", "FOLOMANA"),
    ("4404", "KOKRY"),  # "KOKRY CENTRE"
    ("4406", "MATOMO"),
    ("4407", "NONIMPEBOUGOU"),  # "MONIMPEBOUGOU"
    ("4409", "SANA"),
    ("4410", "SOULEYE"),
    ("4411", "TONGUE"),
    ("4502", "DIABALY"),
    ("4503", "DOGOFRY"),
    ("4505", "MARIKO"),
    ("4506", "NAMPALARI"),
    ("4507", "POGO"),
    ("4508", "SIRIBALA"),
    ("4510", "SOKOLO"),
    ("4511", "TORIDAGA-KO"),  # "TORIDAGA KO"
    ("4512", "YEREDON SANIONA"),
    ("4601", "COMMUNE DE SAN"),  # "SAN"
    ("4602", "BARAMANDOUGOU"),
    ("4604", "DIAKOUROUNA"),
    ("4605", "DIELI"),
    ("4607", "FION"),
    ("4608", "KANIEGUE"),
    ("4609", "KARABA"),
    ("4611", "KAVA"),
    ("4612", "MORIBILA"),
    ("4613", "N'GOA"),
    ("4615", "NIAMANA"),
    ("4616", "NIASSO"),
    ("4617", "OUOLON"),
    ("4619", "SOMO"),
    ("4620", "SOUROUNTOUNA"),
    ("4621", "SY"),
    ("4623", "TENENI"),
    ("4624", "TOURAKOLOMBA"),
    ("4701", "TOMINIAN"),
    ("4702", "BENENA"),
    ("4704", "FANGASSO"),
    ("4705", "KOULA"),  # "KOULANDOUGOU"
    ("4706", "LANFIALA"),
    ("4708", "MANDIAKUY"),
    ("4709", "OUAN"),
    ("4711", "TIMISSA"),
    ("4712", "YASSO"),
    ("5101", "COMMUNE DE MOPTI"),  # "MOPTI"
    ("5103", "BORONDOUGOU"),
    ("5104", "DIALLOUBE"),
    ("5105", "FATOMA"),
    ("5107", "KOROMBANA"),
    ("5108", "KOUBAYE"),
    ("5110", "OURO-MODI"),  # "OURO MODI"
    ("5111", "OUROUBE DOUDE"),  # "OUROBE DOUDDE"
    ("5112", "SASALBE"),
    ("5114", "SOCOURA"),
    ("5115", "SOYE"),
    ("5202", "BARA SARA"),
    ("5203", "BORKO"),
    ("5204", "DANDOLI"),
    ("5206", "DOGANI BERE"),
    ("5207", "DOUCOUMBO"),  # "DOUCOMBO"
    ("5208", "DOUROU"),
    ("5210", "KENDIE"),  # "DENDIE"
    ("5211", "LOWOL GUEOU"),
    ("5212", "METOUMOU"),
    ("5214", "PELOU"),
    ("1210", "NIAMBIA"),
    ("1211", "OUALIA"),
    ("1212", "SIDIBELA"),
    ("1213", "TOMORA"),
    ("0", "ETRANGER"),
]


def _oracoms_for(cercle_id):
    return [item for item in oracom if item[0].startswith(cercle_id)]


def _match(name, oraitems):
    def norm(s):
        return s.strip().lower()

    for oracomid, oracomname in oraitems:
        if norm(oracomname) == norm(name):
            return oracomid

    print(name + ":: " +
          " -- ".join(["{}/{}".format(*item) for item in oraitems]))
    raise


def _oraid_for(xlsitem):
    commune_slug, commune_name, cercle_slug = xlsitem
    cercle_id = get_cercle_id(cercle_slug)
    oracomid = _match(commune_name, _oracoms_for(cercle_id))
    return oracomid


def matchall():
    print('communes = {')
    for xlsitem in xlscom:
        print("    '{}': '{}',".format(_oraid_for(xlsitem), xlsitem[0]))
    print('}')
