#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 nu

import os
import string
import subprocess
import unicodedata

import iso8601

from anamdesktop import IS_MAC, VERSION

# list of hamed-prepared attachments that we care about
VALID_ATTACHMENTS = ('acte-naissance',
                     'acte-mariage',
                     'certificat-frequentation',
                     'certificat-medical',
                     'certificat-indigence')


def datetotext(adate):
    return adate.strftime("%d %B %Y, %Hh%M")


def isototext(text):
    ''' ISO 8601 text to datetime object '''
    return datetotext(iso8601.parse_date(text))


def to_ascii(text):
    ''' convert text to ASCII, ignoring unmtachable characters '''
    return unicodedata.normalize('NFKD', text) \
        .encode('ASCII', 'ignore').decode()


def slugify_for_disk(text):
    ''' text to safe-for-disk slug. Used by `hamed` '''
    valid_chars = "-_.() {l}{d}".format(
        l=string.ascii_letters, d=string.digits)
    slug = unicodedata.normalize('NFKD', text)
    return "".join([c for c in slug if c in valid_chars])


def get_folder_name(identifier, last_name, first_name):
    ''' target folder name as generated by `hamed` on disk '''
    return slugify_for_disk("{ident}-{last} {first}".format(
        ident=identifier,
        last=last_name.strip().upper(),
        first=first_name.strip().title()))


def open_file(fpath):
    ''' open external file for usage in third-party app '''
    if IS_MAC:
        subprocess.call(['open', fpath])
    else:
        os.startfile(fpath)


def get_version():
    return ".".join([str(i) for i in VERSION])
